version: '3.1'

services:
  db:
    image: mysql
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - my-datavolume:/var/lib/mysql
    networks:
      - external
volumes:
  my-datavolume:
networks:
  external:
    name: network_name